### ISSUE TITLE
Error: spawn python ENOENT, on Windows

### ISSUE THREAD

**Issue by gmeligio** [CodeWithSwastik/vscode.py#37]
vscode-ext: 1.5.4
vscode: 1.62.3
Windows: 21H1 (19043.1348)

I was getting `Error: spawn python ENOENT` when running the example https://github.com/CodeWithSwastik/vscode-ext/blob/main/examples/hello_world.py

```
[2021-11-21 20:59:10.224] [renderer16] [error] spawn python ENOENT: Error: spawn python ENOENT
	at Process.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Following the suggestions in https://stackoverflow.com/a/54515183 
I used the already present `osvar` to add `spawnOptions` to all the spawn calls in the generated `extension.js`

```js
const osvar = process.platform;
spawnOptions = {shell: osvar == 'win32'}
```

I might be able to create a PR to solve this issue. Would the PR be reviewed? Is there any guidance on how to contribute?

**Comment by gmeligio** [comment]
Thank you for the update. It's understandable. I'm not currently developing in Python, but I'll see if I can test in the coming weeks.
