### ISSUE TITLE
Error in setting up the virtual environment... 

### ISSUE THREAD

**Issue by SmartManoj** [CodeWithSwastik/vscode.py#49]
Version: 2.0.0a5
```
Setting up the virtual environment... 
Traceback (most recent call last):
  File "c:\Users\smart\Desktop\PappuAI\Pappu.py", line 15, in <module>
    ext.run()
  File "C:\Python310\lib\site-packages\vscode\extension.py", line 178, in run
    build(self)
  File "C:\Python310\lib\site-packages\vscode\compiler.py", line 132, in build
    venv.create("./venv", with_pip=True)
  File "C:\Python310\lib\venv\__init__.py", line 412, in create
    builder.create(env_dir)
  File "C:\Python310\lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\Python310\lib\venv\__init__.py", line 298, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by SmartManoj** [comment]
Maybe due to activating `venv` from the popup during installation.
